/* eslint-disable jsx-a11y/iframe-has-title */
import React, { useEffect, useState } from "react";
import { jsPDF } from "jspdf";

const App = () => {
  const [text, setText] =
    useState(`doc.text("This is the default font.", 20, 20);

doc.setFont("courier", "normal");
doc.text("This is courier normal.", 20, 30);

doc.setFont("times", "italic");
doc.text("This is times italic.", 20, 40);

doc.setFont("helvetica", "bold");
doc.text("This is helvetica bold.", 20, 50);

doc.setFont("courier", "bolditalic");
doc.text("This is courier bolditalic.", 20, 60);

doc.setFont("times", "normal");
doc.text("This is centred text.", 105, 80, null, null, "center");
doc.text("And a little bit more underneath it.", 105, 90, null, null, "center");
doc.text("This is right aligned text", 200, 100, null, null, "right");
doc.text("And some more", 200, 110, null, null, "right");
doc.text("Back to left", 20, 120);

doc.text("10 degrees rotated", 20, 140, null, 10);
doc.text("-10 degrees rotated", 20, 160, null, -10);`);

  const executeJSCode = () => {
    try {
      const pdf = new jsPDF("a4");
      const generatedText = `function generatePDF(doc) { 
        ${text}
      }
      `;
      // Use 'eval' to execute the provided code
      // eslint-disable-next-line no-eval
      eval(`(${generatedText})(pdf);`);

      // Get the content generated by the jsPDF commands
      const pdfContent = pdf.output("datauristring");

      // Add the generated content to the iframe source to display it
      document.getElementById("docpdf").src = pdfContent;
    } catch (error) {
      console.error("Error executing JS code:", error);
    }
  };

  useEffect(() => {
    generatePDF();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [text]);

  const generatePDF = () => {
    executeJSCode();
  };

  return (
    <div
      style={{
        display: "flex",
        height: "100vh",
      }}
    >
      <div
        style={{
          flex: 1,
          padding: "20px",
          overflowY: "auto",
        }}
      >
        <textarea
          id="editor"
          style={{
            width: "100%",
            height: "100%",
          }}
          value={text}
          onChange={(e) => setText(e.target.value)}
        />
        <button onClick={generatePDF} style={{ marginTop: "10px" }}>
          Generate PDF
        </button>
      </div>
      <div
        style={{
          flex: 1,
          padding: "20px",
          backgroundColor: "#EEE",
          overflowY: "auto",
        }}
      >
        <iframe
          id="docpdf"
          style={{
            width: "100%",
            height: "100%",
            border: "none",
          }}
        >
          PDF goes here
        </iframe>
      </div>
    </div>
  );
};

export default App;
